//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagement.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public string ID { get; set; }
        public string IDTABLE { get; set; }
        public string BILL1 { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
    }
}
