//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagement.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public string ID { get; set; }
        public string NAMEPROD { get; set; }
        public string CATEGORYID { get; set; }
        public int PRICE { get; set; }
        public int BOUGHT { get; set; }
        public int SOLD { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
    
        public virtual category category { get; set; }
    }
}
